package ${modelPackage}.base;

<#list schema.getImports(config) as imported>
import ${imported.javaType};
</#list>

/**
 * Please don't modify this class manually.
 * This class is generated by code-mother plugin.
 */
public class Base${schema.modelName} {

<#list schema.columnDefList as column>
    protected ${config.toShortJavaType(column)} ${column.javaName};
</#list>

<#list schema.columnDefList as column>
    public ${config.toShortJavaType(column)} get${column.javaName?cap_first}() {
        <#if column.type == 'Date'>
        if ( null != this.${column.javaName} ) {
        return new Date(this.${column.javaName}.getTime());
        } else {
        return null;
        }
        <#else>
        return this.${column.javaName};
        </#if>
    }

    public void set${column.javaName?cap_first} (${config.toShortJavaType(column)} value) {
        <#if column.type == 'Date'>
        if (value != null) {
        this.${column.javaName} = new Date(value.getTime());
        } else {
        this.${column.javaName} = null;
        }
        <#else>
        this.${column.javaName} = value;
        </#if>
    }
</#list>

}